const socket=io(); const $=s=>document.querySelector(s);
let room=null,myId=null,selectedDifficulty=100,selectedMode='first5',selectedPlayStyle='duel',quickSearching=false,timerRAF=null,countdownRAF=null,lastEndKey='';
const lobby=$('#lobby'),game=$('#game'),daily=$('#daily');
const tokenKey='nhTokenV5',profileKey='nhProfileV5',roomKey='nhRoomV5';
let playerToken=localStorage.getItem(tokenKey)||((crypto.randomUUID&&crypto.randomUUID())||`${Date.now()}-${Math.random()}`); localStorage.setItem(tokenKey,playerToken);
let profile=loadProfile();
function loadProfile(){try{return Object.assign({xp:0,wins:0,losses:0,games:0,finds:0,bestMs:null,dailyBest:{}},JSON.parse(localStorage.getItem(profileKey)||'{}'))}catch{return {xp:0,wins:0,losses:0,games:0,finds:0,bestMs:null,dailyBest:{}}}}
function saveProfile(){localStorage.setItem(profileKey,JSON.stringify(profile));renderProfile()}
const ranks=[['Bronze',0],['Silver',500],['Gold',1200],['Platinum',2200],['Diamond',3500],['Master',5200],['Legend',7500]];
function rankInfo(xp=profile.xp){let i=0;for(let n=0;n<ranks.length;n++)if(xp>=ranks[n][1])i=n;const cur=ranks[i],next=ranks[i+1];return {name:cur[0],floor:cur[1],next:next?.[1]||cur[1]+2500}}
function renderProfile(){const r=rankInfo(),pct=Math.min(100,Math.max(0,(profile.xp-r.floor)/(r.next-r.floor)*100));$('#profileCard').innerHTML=`<div><div class="profileRank">${r.name} · ${profile.xp} XP</div><div class="playerStats">${profile.wins}W · ${profile.losses}L · ${profile.games} games · ${profile.bestMs?`best ${(profile.bestMs/1000).toFixed(2)}s`:'no best yet'}</div><div class="xpBar"><i style="width:${pct}%"></i></div></div><strong>${Math.round(pct)}%</strong>`}
renderProfile(); $('#nameInput').value=localStorage.getItem('nhName')||'';
function name(){const n=$('#nameInput').value.trim().slice(0,18)||'Player';localStorage.setItem('nhName',n);return n}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function vibrate(p=25){try{navigator.vibrate?.(p)}catch{}} function flash(k){const e=$('#flash');e.className=`flash ${k} show`;setTimeout(()=>e.classList.remove('show'),220)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function setView(v){lobby.classList.toggle('hidden',v!=='lobby');game.classList.toggle('hidden',v!=='game');daily.classList.toggle('hidden',v!=='daily')}
function showFriend(){quickSearching=false;socket.emit('quick:cancel');$('#quickPanel').classList.add('hidden');$('#friendPanel').classList.remove('hidden')}
$('#playFriendBtn').onclick=showFriend;
$('#quickPlayBtn').onclick=()=>{const n=name();$('#friendPanel').classList.add('hidden');$('#quickPanel').classList.remove('hidden');$('#lobbyMsg').textContent='';quickSearching=true;socket.emit('quick:join',{name:n,playerToken},res=>{if(!res?.ok){quickSearching=false;$('#quickPanel').classList.add('hidden');$('#lobbyMsg').textContent=res?.error||'Could not search.'}})};
$('#cancelQuickBtn').onclick=()=>{quickSearching=false;socket.emit('quick:cancel');$('#quickPanel').classList.add('hidden')};
socket.on('quick:matched',data=>{quickSearching=false;$('#quickPanel').classList.add('hidden');enterRoom(data);toast('Opponent found!')});
for(const [id,key,setter] of [['difficultyPicker','difficulty',v=>selectedDifficulty=+v],['stylePicker','style',v=>selectedPlayStyle=v],['modePicker','mode',v=>selectedMode=v]]){$(`#${id}`).onclick=e=>{const b=e.target.closest('button[data-value]');if(!b)return;[...$(`#${id}`).querySelectorAll('button')].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');setter(b.dataset.value)}}
$('#createBtn').onclick=()=>socket.emit('room:create',{name:name(),difficulty:selectedDifficulty,mode:selectedMode,playStyle:selectedPlayStyle,playerToken},res=>res?.ok?enterRoom(res):$('#lobbyMsg').textContent=res?.error||'Could not create room');
$('#joinBtn').onclick=()=>socket.emit('room:join',{code:$('#codeInput').value,name:name(),playerToken},res=>res?.ok?enterRoom(res):$('#lobbyMsg').textContent=res?.error||'Could not join');
function enterRoom(data){room=data.room;myId=data.playerId;playerToken=data.playerToken||playerToken;localStorage.setItem(tokenKey,playerToken);localStorage.setItem(roomKey,room.code);setView('game');renderRoom()}
socket.on('room:update',r=>{if(!room||r.code!==room.code)return;room=r;renderRoom()});
socket.on('room:kicked',d=>{toast(d.message||'Removed');home()});socket.on('room:closed',d=>{toast(d.message||'Room closed');home()});
socket.on('game:miss',({number})=>{const b=document.querySelector(`.num[data-n="${number}"]`);b?.classList.add('miss');setTimeout(()=>b?.classList.remove('miss'),260);flash('bad');vibrate([20,30,20])});
socket.on('game:found',r=>{const b=document.querySelector(`.num[data-n="${r.number}"]`);b?.classList.add('hit');flash('good');vibrate([25,30,60]);toast(`${r.finderName} found ${r.number} in ${(r.elapsedMs/1000).toFixed(2)}s`)});
socket.on('game:ended',d=>{room=d.room;renderRoom();showResult()});
function renderRoom(){if(!room)return;$('#roomCode').textContent=room.code;$('#roundNum').textContent=room.round;const mode=room.mode==='first5'?['FIRST TO','5']:room.mode==='first10'?['FIRST TO','10']:['MATCH','2:00'];$('#modeLabel').textContent=mode[0];$('#modeValue').textContent=mode[1];document.documentElement.style.setProperty('--cols',room.difficulty<=50?8:room.difficulty<=100?10:12);$('#numberInput').max=room.difficulty;renderScore();renderBoard();renderState();renderTimer();renderCountdown();if(room.status==='ended')showResult()}
function renderScore(){$('#scoreBar').innerHTML=room.players.map(p=>`<div class="playerCard ${p.id===myId?'you':''}"><div class="playerName">${esc(p.name)}${p.id===myId?' · YOU':''}${p.connected?'':' · offline'}</div><div class="score">${p.score}</div><div class="playerStats">${p.finds} finds · ${p.wrongTaps} misses${p.fastestFindMs?` · ${(p.fastestFindMs/1000).toFixed(2)}s best`:''}</div></div>`).join('')}
function renderBoard(){const html=room.board.map((n,i)=>`<button class="num ${room.found.includes(n)?'found':''}" data-n="${n}" style="--rot:${((n*17+i*11)%19)-9}deg">${n}</button>`).join('');$('#board').innerHTML=html;$('#board').onclick=e=>{const b=e.target.closest('.num');if(!b||room.found.includes(+b.dataset.n))return;const n=+b.dataset.n;if(room.playStyle==='classic'&&room.currentCallerId===myId&&room.target===null){$('#numberInput').value=n;return}socket.emit('game:find',{number:n},()=>{})}}
function renderState(){const waiting=room.players.length<2;$('#waitingControls').classList.toggle('hidden',!waiting);const classic=room.playStyle==='classic',caller=room.currentCallerId===myId;$('#callerControls').classList.toggle('hidden',waiting||!classic||!caller||room.status==='ended');$('#finderControls').classList.toggle('hidden',waiting||room.status==='ended'||(classic&&caller));$('#removePlayerBtn').classList.toggle('hidden',room.hostId!==myId||room.players.length<2);if(waiting){$('#turnText').textContent='WAITING FOR PLAYER';$('#targetText').textContent='Invite a friend'}else if(room.status==='ended'){ $('#turnText').textContent='MATCH COMPLETE';$('#targetText').textContent='See results'}else if(room.target!=null){$('#turnText').textContent=room.playStyle==='duel'?'BOTH PLAYERS HUNT':'FIND IT';$('#targetText').textContent=`FIND ${room.target}`}else{$('#turnText').textContent=room.playStyle==='duel'?'NEXT ROUND':'YOUR MOVE';$('#targetText').textContent=classic?(caller?'Call a number':'Waiting for caller'):'Get ready'}}
function renderTimer(){cancelAnimationFrame(timerRAF);const tick=()=>{if(!room)return;let remain=room.roundLimitMs||20000,label='READY';if(room.target!=null&&room.searchStartsAt){const now=Date.now();if(now<room.searchStartsAt){remain=room.roundLimitMs;label='GET READY'}else{remain=Math.max(0,room.searchStartsAt+room.roundLimitMs-now);label='HUNT'}}else if(room.mode==='timed'&&room.matchEndsAt){remain=Math.max(0,room.matchEndsAt-Date.now());label='MATCH'}$('#timerLabel').textContent=label;$('#timerText').textContent=(remain/1000).toFixed(1);$('#timerBar').style.width=`${Math.max(0,Math.min(100,remain/(room.roundLimitMs||20000)*100))}%`;timerRAF=requestAnimationFrame(tick)};tick()}
function renderCountdown(){cancelAnimationFrame(countdownRAF);const ov=$('#countdown');if(!room?.countdownStartedAt||!room?.searchStartsAt){ov.classList.add('hidden');return}const tick=()=>{const left=room.searchStartsAt-Date.now();if(left<=0){ov.classList.add('hidden');return}ov.classList.remove('hidden');$('#countdownText').textContent=Math.ceil(left/1000);countdownRAF=requestAnimationFrame(tick)};tick()}
$('#callBtn').onclick=()=>socket.emit('game:call',{number:+$('#numberInput').value},res=>{if(!res?.ok)$('#gameMsg').textContent=res?.error||'Could not call';else $('#numberInput').value=''});$('#randomBtn').onclick=()=>socket.emit('game:random',{},res=>{if(res?.ok)$('#numberInput').value=res.number;else $('#gameMsg').textContent=res?.error||'Could not pick'});
function shareRoom(){if(!room)return;const u=new URL(location.href);u.searchParams.set('room',room.code);const text=`Join my Number Hunt room ${room.code}`;navigator.share?navigator.share({title:'Number Hunt',text,url:u.toString()}).catch(()=>{}):navigator.clipboard?.writeText(u.toString()).then(()=>toast('Invite link copied'))} $('#inviteBtn').onclick=shareRoom;$('#roomCode').onclick=shareRoom;
$('#leaveGameBtn').onclick=()=>{if(!room)return home();if(!confirm(room.hostId===myId?'Leave and close this room?':'Leave this game?'))return;socket.emit('room:leave',{},()=>home())};$('#removePlayerBtn').onclick=()=>{const p=room?.players.find(x=>x.id!==myId);if(p&&confirm(`Remove ${p.name}?`))socket.emit('room:kick',{playerId:p.id},()=>{})};
function awardMatchXP(){if(!room||room.status!=='ended')return 0;const key=`${room.code}:${room.endedAt}`;if(lastEndKey===key||localStorage.getItem('nhLastAward')===key)return 0;lastEndKey=key;localStorage.setItem('nhLastAward',key);const me=room.players.find(p=>p.id===myId);if(!me)return 0;const win=room.winnerId===myId,tie=!room.winnerId;let gained=(win?120:tie?70:45)+me.finds*10;profile.games++;if(win)profile.wins++;else if(!tie)profile.losses++;profile.finds+=me.finds;if(me.fastestFindMs)profile.bestMs=profile.bestMs?Math.min(profile.bestMs,me.fastestFindMs):me.fastestFindMs;profile.xp+=gained;saveProfile();return gained}
function showResult(){if(!room||room.status!=='ended')return;const gained=awardMatchXP();const me=room.players.find(p=>p.id===myId),opp=room.players.find(p=>p.id!==myId),win=room.winnerId===myId,tie=!room.winnerId;$('#winnerTitle').textContent=tie?'Draw!':win?'You win!':`${opp?.name||'Opponent'} wins`;$('#winnerSubtitle').textContent=win?'Fast eyes. Nice work.':tie?'Couldn’t separate you two.':'Run it back.';$('#rankChange').textContent=gained?`+${gained} XP · ${rankInfo().name}`:`${rankInfo().name} · ${profile.xp} XP`;$('#finalStats').innerHTML=`<div class="statRow"><span>Your finds</span><strong>${me?.finds||0}</strong></div><div class="statRow"><span>Fastest find</span><strong>${me?.fastestFindMs?`${(me.fastestFindMs/1000).toFixed(2)}s`:'—'}</strong></div><div class="statRow"><span>Accuracy</span><strong>${me?.attempts?`${Math.round(me.finds/me.attempts*100)}%`:'—'}</strong></div>`;$('#resultModal').classList.remove('hidden')}
$('#rematchBtn').onclick=()=>socket.emit('game:new',{difficulty:room.difficulty,mode:room.mode,playStyle:room.playStyle},res=>{if(res?.ok){$('#resultModal').classList.add('hidden');room=res.room;renderRoom()}});$('#homeBtn').onclick=()=>{socket.emit('room:leave',{},()=>{});home()};
function home(){$('#resultModal').classList.add('hidden');room=null;myId=null;localStorage.removeItem(roomKey);setView('lobby');renderProfile()}
// Daily challenge: deterministic by UTC date, 10 targets, local best and XP once per day.
let d={active:false,board:[],targets:[],idx:0,start:0,targetStart:0,found:0,wrong:0,raf:null,date:''};
function seedHash(str){let h=2166136261;for(const c of str){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function dailyData(date){const r=rng(seedHash(`numberhunt-${date}`)),a=Array.from({length:100},(_,i)=>i+1);for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}const t=[];while(t.length<10){const n=1+Math.floor(r()*100);if(!t.includes(n))t.push(n)}return{board:a,targets:t}}
$('#dailyBtn').onclick=startDaily;function startDaily(){name();const date=new Date().toISOString().slice(0,10),x=dailyData(date);d={active:true,board:x.board,targets:x.targets,idx:0,start:Date.now()+3000,targetStart:Date.now()+3000,found:0,wrong:0,raf:null,date};setView('daily');$('#dailyDate').textContent=date;$('#dailyBest').textContent=profile.dailyBest?.[date]?`${(profile.dailyBest[date]/1000).toFixed(1)}s`:'—';$('#dailyBoard').innerHTML=d.board.map((n,i)=>`<button class="num" data-n="${n}" style="--rot:${((n*13+i*7)%19)-9}deg">${n}</button>`).join('');$('#dailyTarget').textContent=d.targets[0];$('#dailyFound').textContent='0/10';$('#dailyXp').textContent='+0 XP';runDailyCountdown();runDailyTimer()}
function runDailyCountdown(){const ov=$('#countdown');const tick=()=>{const left=d.start-Date.now();if(left<=0){ov.classList.add('hidden');return}ov.classList.remove('hidden');$('#countdownText').textContent=Math.ceil(left/1000);requestAnimationFrame(tick)};tick()}
$('#dailyBoard').onclick=e=>{const b=e.target.closest('.num');if(!b||!d.active||Date.now()<d.start)return;const n=+b.dataset.n;if(n!==d.targets[d.idx]){d.wrong++;b.classList.add('miss');setTimeout(()=>b.classList.remove('miss'),250);flash('bad');vibrate([15,20,15]);return}b.classList.add('found','hit');d.found++;d.idx++;flash('good');vibrate(30);$('#dailyFound').textContent=`${d.found}/10`;if(d.idx>=10)return finishDaily();d.targetStart=Date.now();$('#dailyTarget').textContent=d.targets[d.idx]}
function runDailyTimer(){cancelAnimationFrame(d.raf);const tick=()=>{if(!d.active)return;const now=Date.now(),elapsed=Math.max(0,now-d.start)+d.wrong*500;$('#dailyTimer').textContent=(elapsed/1000).toFixed(1);$('#dailyTimerBar').style.width=`${Math.max(5,100-(elapsed/90000*100))}%`;d.raf=requestAnimationFrame(tick)};tick()}
function finishDaily(){d.active=false;cancelAnimationFrame(d.raf);const total=Math.max(0,Date.now()-d.start)+d.wrong*500;const old=profile.dailyBest?.[d.date]||null;if(!profile.dailyBest)profile.dailyBest={};if(!old||total<old)profile.dailyBest[d.date]=total;const awardKey=`nhDailyAward-${d.date}`;let gained=0;if(!localStorage.getItem(awardKey)){gained=150;profile.xp+=gained;localStorage.setItem(awardKey,'1')}saveProfile();$('#dailyXp').textContent=`+${gained} XP`;$('#dailyResultTitle').textContent=old&&total>=old?'Challenge complete':'New daily best!';$('#dailyResultText').textContent=`${(total/1000).toFixed(1)}s · ${d.wrong} wrong taps${gained?` · +${gained} XP`:''}`;$('#dailyModal').classList.remove('hidden')}
$('#dailyAgainBtn').onclick=()=>{$('#dailyModal').classList.add('hidden');startDaily()};$('#dailyHomeBtn').onclick=()=>{$('#dailyModal').classList.add('hidden');home()};$('#dailyBackBtn').onclick=()=>{d.active=false;cancelAnimationFrame(d.raf);home()};
const roomParam=new URL(location.href).searchParams.get('room');if(roomParam){$('#codeInput').value=roomParam.toUpperCase();showFriend()}
socket.on('connect',()=>{const code=localStorage.getItem(roomKey);if(code&&!room)socket.emit('room:resume',{code,playerToken},res=>{if(res?.ok)enterRoom(res);else localStorage.removeItem(roomKey)})});
